---
title: Stackbit Exto Theme
baseURL: "/"
params:
  color_scheme: light
  accent_color: yellow
  header:
    title: Real e Barreiros Advogados
    has_nav: true
    logo_img: "/images/LOGO_2_sem_fundo 3.png"
  footer:
    content: "&copy; Stackbit-Exto. All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
